stages:
    - web_build
    - web_push
web_build:
    stage: web_build
    only:
        - tag
    script:
        - docker build -t d.thcen.com/qianye.web -t d.thcen.com/qianye.web:$CI_COMMIT_REF_NAME .
web_push:
    stage: web_push
    only:
        - tag
    script:
        - docker push d.thcen.com/qianye.web
    dependencies:
        - web_build